In [ ]:
import pandas as pd

df = pd.read_csv('employee_data.csv.csv')

df.head()

,Emp_ID,Emp_Name,Age,Department,Job_Position,Location,Salary,Experience
0,101,Rahul Sharma,28,IT,Data Analyst,Hyderabad,45000,3
1,102,Priya Reddy,32,HR,HR Manager,Bangalore,60000,8
2,103,Amit Kumar,25,IT,Software Engineer,Chennai,50000,2
3,104,Neha Singh,30,Finance,Accountant,Mumbai,55000,5
4,105,Suresh Rao,35,IT,Project Manager,Hyderabad,80000,10

In [ ]:
df.dtypes

Emp_ID           int64
Emp_Name        object
Age              int64
Department      object
Job_Position    object
Location        object
Salary           int64
Experience       int64
dtype: object

In [ ]:
df.info

<bound method DataFrame.info of    Emp_ID      Emp_Name  Age Department         Job_Position   Location  \
0     101  Rahul Sharma   28         IT         Data Analyst  Hyderabad
1     102   Priya Reddy   32         HR           HR Manager  Bangalore
2     103    Amit Kumar   25         IT    Software Engineer    Chennai
3     104    Neha Singh   30    Finance           Accountant     Mumbai
4     105    Suresh Rao   35         IT      Project Manager  Hyderabad
5     106  Anjali Verma   27  Marketing  Marketing Executive       Pune
6     107   Rohan Gupta   29         IT       Data Scientist  Bangalore
7     108    Kavya Nair   31    Finance    Financial Analyst    Chennai
8     109  Vikram Patel   26         HR            Recruiter  Hyderabad
9     110   Meena Joshi   33  Marketing    Marketing Manager     Mumbai

   Salary  Experience
0   45000           3
1   60000           8
2   50000           2
3   55000           5
4   80000          10
5   42000           3
6   75000           6
7   58000           7
8   40000           2
9   70000           9  >

In [ ]:
df.head()

,Emp_ID,Emp_Name,Age,Department,Job_Position,Location,Salary,Experience
0,101,Rahul Sharma,28,IT,Data Analyst,Hyderabad,45000,3
1,102,Priya Reddy,32,HR,HR Manager,Bangalore,60000,8
2,103,Amit Kumar,25,IT,Software Engineer,Chennai,50000,2
3,104,Neha Singh,30,Finance,Accountant,Mumbai,55000,5
4,105,Suresh Rao,35,IT,Project Manager,Hyderabad,80000,10

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Emp_ID        10 non-null     int64
 1   Emp_Name      10 non-null     object
 2   Age           10 non-null     int64
 3   Department    10 non-null     object
 4   Job_Position  10 non-null     object
 5   Location      10 non-null     object
 6   Salary        10 non-null     int64
 7   Experience    10 non-null     int64
dtypes: int64(4), object(4)
memory usage: 772.0+ bytes

In [ ]:
df.dtypes

Emp_ID           int64
Emp_Name        object
Age              int64
Department      object
Job_Position    object
Location        object
Salary           int64
Experience       int64
dtype: object

In [ ]:
df.set_index("Emp_ID", inplace=True)
df

,Emp_Name,Age,Department,Job_Position,Location,Salary,Experience
Emp_ID,,,,,,,
101,Rahul Sharma,28,IT,Data Analyst,Hyderabad,45000,3
102,Priya Reddy,32,HR,HR Manager,Bangalore,60000,8
103,Amit Kumar,25,IT,Software Engineer,Chennai,50000,2
104,Neha Singh,30,Finance,Accountant,Mumbai,55000,5
105,Suresh Rao,35,IT,Project Manager,Hyderabad,80000,10
106,Anjali Verma,27,Marketing,Marketing Executive,Pune,42000,3
107,Rohan Gupta,29,IT,Data Scientist,Bangalore,75000,6
108,Kavya Nair,31,Finance,Financial Analyst,Chennai,58000,7
109,Vikram Patel,26,HR,Recruiter,Hyderabad,40000,2
110,Meena Joshi,33,Marketing,Marketing Manager,Mumbai,70000,9

In [ ]:
df.loc[105]

Emp_Name             Suresh Rao
Age                          35
Department                   IT
Job_Position    Project Manager
Location              Hyderabad
Salary                    80000
Experience                   10
Name: 105, dtype: object

In [ ]:
df[df["Department"]=="IT"]

,Emp_Name,Age,Department,Job_Position,Location,Salary,Experience
Emp_ID,,,,,,,
101,Rahul Sharma,28,IT,Data Analyst,Hyderabad,45000,3
103,Amit Kumar,25,IT,Software Engineer,Chennai,50000,2
105,Suresh Rao,35,IT,Project Manager,Hyderabad,80000,10
107,Rohan Gupta,29,IT,Data Scientist,Bangalore,75000,6

In [ ]:
df[df["Salary"] > 60000]

,Emp_Name,Age,Department,Job_Position,Location,Salary,Experience
Emp_ID,,,,,,,
105,Suresh Rao,35,IT,Project Manager,Hyderabad,80000,10
107,Rohan Gupta,29,IT,Data Scientist,Bangalore,75000,6
110,Meena Joshi,33,Marketing,Marketing Manager,Mumbai,70000,9

In [ ]:
df[df["Location"]=="Hyderabad"]

,Emp_Name,Age,Department,Job_Position,Location,Salary,Experience
Emp_ID,,,,,,,
101,Rahul Sharma,28,IT,Data Analyst,Hyderabad,45000,3
105,Suresh Rao,35,IT,Project Manager,Hyderabad,80000,10
109,Vikram Patel,26,HR,Recruiter,Hyderabad,40000,2

In [ ]:
df[(df["Department"]=="IT") & (df["Salary"]>50000)]

,Emp_Name,Age,Department,Job_Position,Location,Salary,Experience
Emp_ID,,,,,,,
105,Suresh Rao,35,IT,Project Manager,Hyderabad,80000,10
107,Rohan Gupta,29,IT,Data Scientist,Bangalore,75000,6

In [ ]:
df.shape

(10, 7)

In [ ]:
pd.read_csv("employee.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'employee.csv'

In [ ]:
Emp_ID,Emp_Name,Salary
101,Rahul,45000
102,Priya
103,Amit,50000,Extra

NameError: name 'Emp_ID' is not defined

In [ ]:
pd.read_csv("corrupt_employee.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'corrupt_employee.csv'